version: '3.7'
services:
  attacker:
    build: ./attacker
    ports:
      - "1389:1389"
      - "8080:8080"
    networks:
      mynet:
        aliases:
          - web
  web:
    image: vulhub/apache-druid:25.0.0
    ports:
      - "8888:8888"
    networks:
      mynet:
        aliases:
          - attacker

networks:
  mynet:
    driver: bridge
