version: "3.7"
services:
  attacker:
    build: ./attacker
    ports:
      - "2333:2333"
    networks:
      mynet:
        aliases:
          - bot
  bot:
    build: ./bot
    command: sleep infinity
    networks:
      mynet:
        aliases:
          - attacker

networks:
  mynet:
    driver: bridge