version: '3.7'
services:
  attacker:
    build: ./attacker
    networks:
      mynet:
        aliases:
          - spring
  spring:
    image: vulhub/spring-cloud-gateway:3.1.0
    ports:
      - "8080:8080"
    networks:
      mynet:
        aliases:
          - attacker

networks:
  mynet:
    driver: bridge
