version: "3.7"
services:
  victim:
    image: vulhub/laravel:8.4.2
    ports:
      - "8000:80"
    networks:
      - mynet
  attacker:
    build: ./attacker
    networks:
      - mynet

networks:
  mynet: