version: "3.7"
services:
  victim:
    build: ./victim
    ports:
      - "8000:80"
    networks:
      mynet:
        aliases:
          - attacker

  attacker:
    build: ./attacker
    networks:
      mynet:
        aliases:
          - victim

networks:
  mynet:
    driver: bridge