version: '3.7'
services:
  attacker:
    build: ./attacker
    networks:
      mynet:
        aliases:
          - redis
  redis:
    image: vulhub/redis:5.0.7
    ports:
      - "6379:6379"
    networks:
      mynet:
        aliases:
          - attacker

networks:
  mynet:
    driver: bridge