version: "3.7"

services:
  gethnode-1:
    container_name: gethnode-1
    hostname: gethnode-1
    environment:
      coinbase: 1D371e6885D33591b574A45DDE7567BF0b092F59
      datadir: node1
    image: crazybun/go-eth:2023.5.12
    ports:
      - 8545:8545
      - 8551:8551
      - 30303:30303
    volumes:
      - /f/docker/data/geth:/opt
    networks:
      - mynet

  gethnode-2:
    container_name: gethnode-2
    hostname: gethnode-2
    environment:
      coinbase: 3f671A4BFA16BD278cc0a8c79eDF316363BE98A7
      datadir: node2
    image: crazybun/go-eth:2023.5.12
    ports:
      - 8546:8545
      - 8552:8551
      - 30304:30303
    volumes:
      - /f/docker/data/geth:/opt
    networks:
      - mynet

networks:
  default:
    driver: bridge
  mynet:
    driver: bridge